### ISSUE TITLE
Select Date and customize view row?

### ISSUE THREAD

**Issue by desarrolloddol** [aaronweihe/MonoDroid.TimesSquare#4]
Hello aaron,

thanks to port TimesSquere control to monodroid. I m testing but i have same doubts.

1) I call a "click" event of calendar but visual return error "Java.Lang.RuntimeException: Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead" . I wish that user select a date , open a custom activity.

2) I want add text into a date cell . ¿How can i do it?

Regards

**Comment by aaronweihe** [comment]
1) I'm sorry this feature hasn't been implemented yet. To get the current selected date, you have to call `calendar.SelectedDate`.

2) `MonthView` is where you should be looking for. Check [this line](https://github.com/aaronmix/MonoDroid.TimesSquare/blob/master/MonoDroid.TimesSquare/MonthView.cs#L60) particularly. `cellView.Test` sets the text.

Thanks.

Sorry for the late responses.

**Comment by aaronweihe** [comment]
The latest version now supports `OnDateSelected` event but it's implemented in interface based flavor.

Basically, you need to implement `MonoDroid.TimesSquare.IOnDateSelectedListener` and set `CalendarPickerView`'s listener to it.

The class would be something like this:

```
private class DateSelected : MonoDroid.TimesSquare.IOnDateSelectedListener
{
    private Context _context;
    private CalendarPickerView _calendar;
    public DateSelected(Context context, CalendarPickerView calendar)
    {
        _context = context;
        _calendar = calendar;
    }

    public void OnDateSelected(DateTime date)
    {
        Toast.MakeText(_context, "Selected: " + _calendar.SelectedDate, ToastLength.Short).Show();
    }
}
```

And in your `Activity`:

```
var calendar = FindViewById<CalendarPickerView>(Resource.Id.calendar_view);
calendar.SetOnDateSelectedListener(new DateSelected(this, calendar));
```
