### ISSUE TITLE
Error building on Api level 16

### ISSUE THREAD

**Issue by gregorypilar** [aaronweihe/MonoDroid.TimesSquare#7]
Hi
Im trying to build the library on api level 16 , but I get this errors : 

``` code
Error: No resource found that matches the given name: attr 'android:textAlignment'
```

Full description : 

``` code
C:\Users\Gregory\Downloads\MonoDroid.TimesSquare-master\MonoDroid.TimesSquare\Resources\values\styles.xml(0,0): Error: No resource found that matches the given name: attr 'android:textAlignment'. (MonoDroid.TimesSquare)
```

**Comment by aaronweihe** [comment]
@gregorypilar Sorry to hear that, but I am just back from vacation. I'll look at this ASAP.

**Comment by aaronweihe** [comment]
@gregorypilar `android:textAlignment` was aded in API 17, so try to build the library against level 17+ and it should be resolved.

Also, the same error was reported [here](https://github.com/square/android-times-square/issues/33).
