### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by mohibsheth** [aaronweihe/MonoDroid.TimesSquare#9]
Hi Aaron,

Do you have updates on this library? The original library has been updated recently.

Is this available on Xamarin Component Store already or are you planning on adding it soon?

**Comment by mohibsheth** [comment]
On another note, I can't compile the current version? Can you? I keep getting "Error CS0246: The type or namespace name `CalendarPickerView' could not be found. Are you missing an assembly reference?"

**Comment by mohibsheth** [comment]
The problem was the MonoDroid.TimesSquare project. Its somehow been marked as an Android Application rather than an Android Library. Manually editing the csproj files fixed the issue for me.

The sample builds and runs fine now.

**Comment by aaronweihe** [comment]
Hi,

Sorry I haven't updated the library for a while. Yes, I know the original one has been updated frequently. What happened was I switched a job later last year. Because of that, I no longer have a license of Xamarin Android. I am doing plain old Java Android dev now. :frowning: 

It's not on Component store yet. I am/was planning to. But because of license, things got slowed down. I'll try to get a license soon.

About the compiler error, it was compiled fine and recognized as a library project. I think probably the structure of csproj file got changed at some point.

Thanks! :smiley:

**Comment by mohibsheth** [comment]
:disappointed: :imp: How dare you betray your C# brethren!!

Just kidding, congrats on the new job mate. Though a little but better than never :smile: 

I will send in a PR along to fix that compilation issues. How did you port this library? Manually or you used some tool?

If you could show me how you did it, I could do it for the latest version of the library.

**Comment by aaronweihe** [comment]
LOL! THANKS!

Yes, that'd be awesome! Just send a PR over. I ported manually. Didn't use any tools. I was keeping an eye on each approved PR at the original library, and trying to keep updated with that. I tried doing a binding, but XS throwed me all kinds of weird errors. It wasn't a huge library, so I thought just ported manually. :smiley:

**Comment by mohibsheth** [comment]
What was the last PR in the original library that you ported? I will start porting important changes from after that or have you already started to work on it?

**Comment by aaronweihe** [comment]
I think the past pr was https://github.com/square/android-times-square/pull/123. No, I haven't started yet.

**Comment by mohibsheth** [comment]
Thanks. I will start looking into PR's after that. I would appreciate if
you could help me with a problem I am facing. When I put the
CalendarPickerView in an Activity and do Init in onCreate.. it works fine.
But if I put the same in a fragment (which is added to an activity on
oncreate).. it doesnt render. Do you know why this is so? Have you faced a
similar problem? I just can't get the calendar to work in a fragment :(

EDIT:
The issue was in AXML. Fixed it.
